// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func BuildEvent() (Event, error) {
	message := ProvideMessage()
	greeter := ProvideGreeter(message)
	event, err := ProvideEvent(greeter)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}
