version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "02:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "_"
