pkgname = "db"
output = "graph/db"
wipe = true
add-global-variants = false
no-tests = true

[sqlite3]
dbname = "./mygraphql.db"
[[types]]
[types.match]
name = "created_at"
[types.replace]
type = "time.Time"
