name: Dependabot automation

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dependabot-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 13
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.AUTO_MERGE_BOT_APP_ID }}
          private_key: ${{ secrets.AUTO_MERGE_BOT_PRIVATE_KEY }}
      - name: Approve & enable auto-merge for Dependabot PR
        run: |
          gh pr review --approve "$PR_URL"
          gh pr edit "$PR_URL" -t "(auto merged) $PR_TITLE"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
