name: Create diagram
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Calculate date
        run: echo "DATE=$(date '+%Y-%m-%dT%H:%M:%S%z')" >> "$GITHUB_OUTPUT"
        id: date-generator
      - name: Update diagram
        uses: githubocto/repo-visualizer@0.9.1
        with:
          output_file: "repo-diagram.svg"
          commit_message: "Repo visualizer: updated diagram ${{ steps.date-generator.outputs.DATE }}"
