name: Sync issue
on:
  issues:
    types: [opened]

permissions:
  issues: write
  repository-projects: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Sync issue
        uses: kudoas/sync-issue@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
