name: Sync issue
on:
  issues:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 379658
          private-key: ${{ secrets.PRIMARY_KEY }}
      - uses: actions/checkout@main
      - name: Sync issue
        uses: kudoas/sync-issue@main
        with:
          token: ${{ steps.app-token.outputs.token }}
