name: Pull from GitHub Container Registory
on: push
jobs:
  container-job:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    services:
      golang:
        image: ghcr.io/kudoas/golang:latest
        credentials:
          username: sandbox-auto-merge-bot[bot]
          password: ${{ secrets.AUTO_MERGE_BOT_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
